# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'testPlugin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'pluginOne', :path => "./Sources"

  # Pods for testPlugin

  target 'testPluginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testPluginUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
